### ISSUE TITLE
Allow spaces after opening parenthesis if the following character is !

### ISSUE THREAD

**Issue by michaelcullum** [cs-extended/fig-standards#10]

**Comment by michaelcullum** [comment]
@keradus What would it be like implementing this in CS fixers? I believe you're the lead on PHP-CS-Fixer?

**Comment by keradus** [comment]
It is an exception. And I do not like exception to rules.
That would be exception for `parenthesis` fixer, see: https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/1.11/Symfony/CS/Fixer/PSR2/ParenthesisFixer.php#L18

If one really want he could make his own fixer like existing `logical_not_operators_with_successor_space`.
But IMO adding an exception to existing rule is bad.

**Comment by michaelcullum** [comment]
Okay. On that basis I think this is un-necessary complication.

**Comment by michaelcullum** [comment]
@keradus Your input in general on this PSR throughout it's development would be much appreciated by the way.
