### ISSUE TITLE
Guidelines of newlines after "<?php"

### ISSUE THREAD

**Issue by cryptiklemur** [cs-extended/fig-standards#23]
I couldn't find anything in the PSR's (current or proposed) that talked about newlines after the opening tag (`<?php`).

Right now, from what i can tell, the following are all allowed, due to differing versions of PHP:

``` php
<?php
declare(strict_types=1);

namespace Acme;

// Code
```

``` php
<?php

namespace Acme;

// Code
```

``` php
<?php
namespace Acme;

// Code
```

```
<?php namespace Acme;

// Code
```

**Comment by michaelcullum** [comment]
1ebe95b3aeea5554b2a0d860439e104bd8266fd9

**Comment by cryptiklemur** [comment]
:+1:
