### ISSUE TITLE
declare statement

### ISSUE THREAD

**Issue by keradus** [cs-extended/fig-standards#24]
Hi. I think we need to clarify CS about `declare` keyword.
We know that it should look like this:

``` php
declare(ticks=1);
```

so no spaces at all.

But document doesn't provide any guidelines for second form of declare:

``` php
declare(ticks=1) {
    //some code
}
```
1. is the block form allowed ? (as it is not mentioned in w hole document)
2. should there be a space before `{` ?
3. should there be a spabe after `declare`, as the notation is a bit similar to `if` statement ?

When decided, it should be added to document.

**Comment by michaelcullum** [comment]
Funny you mention this as it came up on IRC yesterday. // @KorvinSzanto @aequasi

What are people's thoughts on this?

My thoughts:
1) It's not forbidden so yes

If we decide to include something about generalised declare statements then:
2) Yes
3) I think keep it the same as other declare blocks to be honest

If there is lack of consensus then we can take this to the ML

**Comment by keradus** [comment]
We have a proposition of fixer for that `declare` statement at PHP CS Fixer for some time too ;)

So exactly as in my example :D
I also think it should be done that way, but the PSR need to cover that case.

**Comment by KorvinSzanto** [comment]
This all sounds fine to me. 
@keradus what do you think about limiting the location of declare statements? Today the ticks declare can go anywhere in the file while the strict types declare can only be the first statement. Should we say that ticks declare has to be the first statement as well?

**Comment by keradus** [comment]
Isn't the same for `encoding` declaration?

For me all decralarion should be done at start of file, but I can imagine the cases when there could be few declaration of same thing but with different value.

Maybe limit the `declare(ticks=1);` form to be at top, and the `declare(ticks=1) {...}` to be where the user wants ?

**Comment by aequasi** [comment]
I just want to reiterate, this is a coding style guide, not a coding standard. I don't really think this is the place for saying whether or not strict types should/must be enabled.

**Comment by keradus** [comment]
Then go to my original question - about spaces ;)

**Comment by michaelcullum** [comment]
@aequasi I don't think that was ever suggested here unless I'm missing something? This is about how to use it, not when to use it. :)

**Comment by cryptiklemur** [comment]
Totally commented in the wrong issue.

**Comment by michaelcullum** [comment]
1ebe95b3aeea5554b2a0d860439e104bd8266fd9

**Comment by keradus** [comment]
Thank you!
