### ISSUE TITLE
Blank line before namespace

### ISSUE THREAD

**Issue by samdark** [cs-extended/fig-standards#28]
Maybe need add rule for blank line before namespace when not presented declare statements?
Now PSR-2 compatible packages use different variants.

For example, code from yii2 app:

```
<?php
namespace common\models;
//other code
```

and code from laravel app:

```
<?php

namespace App;
//other code
```

I propose in PSR-12 apply one of these variants.

Included into https://github.com/php-fig/fig-standards/pull/730

**Comment by glen-84** [comment]
See also https://github.com/php-fig/fig-standards/issues/654 (point 2).

**Comment by michaelcullum** [comment]
This would be included in @Crell's proposal to have the header blocks, always with an empty line in between.

**Comment by samdark** [comment]
This one is addressed allowing both styles i.e. space after `<?php` isn't forced.
