### ISSUE TITLE
Type casting

### ISSUE THREAD

**Issue by hrvoj3e** [cs-extended/fig-standards#29]
Which is correct?

(space after casting) : There MUST be one space after the control structure keyword
I vote for this!

``` php
$number = (int) $_GET['number'];
```

(without space)

``` php
$number = (int)$_GET['number'];
```

I am referring to:
https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-2-coding-style-guide.md#5-control-structures

**Comment by samdark** [comment]
I'm for using it w/o space. Since it's actively used thing, it worth performing two surveys: one for everyone and one for php-fig member projects.

**Comment by hrvoj3e** [comment]
+1 for surveys!

References: https://github.com/cs-extended/fig-standards/issues/30

**Comment by samdark** [comment]
One topic one issue please. Here's general survey: http://goo.gl/forms/I20qCkAnh9 Please send it to everyone you can reach.

**Comment by hrvoj3e** [comment]
Are **_integer, boolean_** valid?
I assumed that PSR-12 allowed only short versions _int, bool_.

PHP manual also uses **int, bool** : http://php.net/manual/en/functions.arguments.php#functions.arguments.type-declaration

See: https://github.com/php-fig/fig-standards/blob/master/proposed/extended-coding-style-guide.md#25-keywords-and-types
The PHP types and keywords array, **int**, true, object, float, false, mixed, **bool**, null, numeric, string, void and resource MUST be in lower case.

**Comment by samdark** [comment]
Yes. I want to get current state of things.

**Comment by SilverFire** [comment]
+1 to no-space option

**Comment by sizeg** [comment]
Vote for one space, it makes the code look cleaner.

**Comment by michaelcullum** [comment]
Korvin and I agree this is out of scope for this PSR.
