### ISSUE TITLE
References coding style

### ISSUE THREAD

**Issue by hrvoj3e** [cs-extended/fig-standards#30]
See: http://php.net/manual/en/language.references.php

``` php
$foo = &$bar; // I vote for this!
```

vs

``` php
$foo = & $bar;
$foo =& $bar;
```

**Comment by michaelcullum** [comment]
:+1: for inclusion on this from me. The first option is most common (I've never seen the latter two and didn't even know it was possible) and the 3rd option violates the operators section.

**Comment by samdark** [comment]
Yeah, I think the first is common one. I'll create a vote so there will be a solid proof for meta doc.

**Comment by samdark** [comment]
http://goo.gl/forms/CHkQLfBxAi

**Comment by michaelcullum** [comment]
Why not just include this in the main survey?

**Comment by samdark** [comment]
Small individual surveys are better. Not taking that much time.

**Comment by michaelcullum** [comment]
Korvin and I discussed this and decided to leave it out as out of scope. We need to be careful this doesn't just become another coding style guide but focusses on important clarifications and adding things relevant to new features.
