### ISSUE TITLE
Style for breaking long lines

### ISSUE THREAD

**Issue by samdark** [cs-extended/fig-standards#31]
``` php
if ($arg1
    || $arg2
    || $arg3)
```

``` php
if ($arg1 ||
    $arg2 ||
    $arg3)
```

``` php
if (
    $arg1
    || $arg2
    || $arg3
)
```

``` php
if (
    $arg1 ||
    $arg2 ||
    $arg3
)
```

``` php
$var = $arg1 ?
'1'
: '0';
```

``` php
$var = $arg1
? '1'
: '0';
```

**Comment by de-salvatierra** [comment]
```
if(
    $var1
        &&
    (
        $var2
            ||
        $var3
    )
) {
    // expression
}
```

**Comment by hrvoj3e** [comment]
I use this only when I have multiple conditions and one of them is complex to read so it makes sense to visually separate each condition part in new line with operator as prefix.

``` php
if (
    $arg1       // each variable is in new line
    || $arg2    // operator is allways as prefix to a variable (easier to comment and to read)
    || $arg3
)
```

``` php
$var = $arg1
? '1'     // operator as prefix to value
: '0';
```

**Comment by keradus** [comment]
I would prefer having braces on it's own lines, and then having operator on the left side.

For ternaries the same, but keep them indented.

``` php
if (
    $foo
    || $bar
)
```

``` php
$var = $foo
    ? $bar
    : $baz;
```

**Comment by michaelcullum** [comment]
Korvin and I looked at this and decided it's way too complex to cover. This is the kind of thing we can leave to individuals to just do what looks appropriate I think.

**Comment by keradus** [comment]
why it's too complex? spec for it doesn't look complex, especially when you define it with example
