### ISSUE TITLE
Clarify LF vs CRLF

### ISSUE THREAD

**Issue by samdark** [cs-extended/fig-standards#32]
See https://groups.google.com/forum/#!topic/php-fig/SH2Gs3sTS-M

**Comment by judgej** [comment]
- `LF` - line feed - 0x0A - \n - used by Unix, Linux and derivatives.
- `CR` - carriage return 0x0D - \r - used by MacOS (up to v9), 80s home computers.
- `CR+LF` - \r\n - DOS and Windows text file line endings.
- `LF+CR` - \n\r - some bastard format used in some specific output files from long ago.

These derive from telex printers, where a `LF` moves the paper on one line, and `CR` moves the carriage to the start of the line. Both were necessary in a telex transmission.

To say PSR-2 used `LF` line endings, IMO unambiguously means, "and none of the other related line endings". So `LF` means _not_ `CR`, or `CR+LF`. I think it is clear.

Does PSR-11 need additional details in its meta-document to expand on what this means? Can't do any harm.

**Comment by samdark** [comment]
Yes, I think it could be elaborated a bit.
