### ISSUE TITLE
Formatting of declare construct

### ISSUE THREAD

**Issue by glen-84** [cs-extended/fig-standards#36]
Can this be added to the survey?

**Position:**
1. Same line as `<?php`
2. Following line
3. Blank line between `<?php` and `declare();`
4. Unspecified

**Argument spacing:**
1. Spaced like assignment and default parameter values (`declare(strict_types = 1);`)
2. No spaces (`declare(strict_types=1);`)
3. Unspecified
# 

(my personal preference is `#3` and `#1`)

**Comment by michaelcullum** [comment]
We clarify what this statement should look like exactly.
> Declare statements MUST contain no spaces and MUST be exactly `declare(strict_types=1)`
(with an optional semi-colon terminator).
