### ISSUE TITLE
Define what empty line is

### ISSUE THREAD

**Issue by samdark** [cs-extended/fig-standards#37]
>  Should empty lines have tabs that align with lines that have characters or should it be fully empty?

See https://groups.google.com/forum/#!topic/php-fig/1mEA_cDA5dM

**Comment by hrvoj3e** [comment]
**Full empty.**
It is better when comparing code as most tools detect tabs/spaces in "empty" lines as differences.
Additional tabs/spaces add to filesize.

**Comment by michaelcullum** [comment]
Indeed. This should be full empty.

**Comment by michaelcullum** [comment]
This was intentionally omitted from PSR-1/2 due to contention and therefore I suspect it will break BC so this is out of scope.

**Comment by samdark** [comment]
There is no BC to break.

**Comment by michaelcullum** [comment]
Of course there is. With projects doing whatever is not chosen to go into PSR-12.

**Comment by samdark** [comment]
Yes, but it's the same for all new rules we introduce such as having or not having blank like after `<?php`.

**Comment by michaelcullum** [comment]
Except that is related to new functionality because it's related to the new strict types declaration and it wasn't discussed the first time around for PSR-1/2 whether or not that should be clarified.

**Comment by samdark** [comment]
For end user it doesn't matter. If we're maintaining backwards compatibility, we should be consistent else the argument isn't valid.

**Comment by michaelcullum** [comment]
A BC break is not the main argument, it is a reduction in the reasoning to break scope.
