### ISSUE TITLE
Either allow or deny assignment alignment

### ISSUE THREAD

**Issue by samdark** [cs-extended/fig-standards#38]
> When assigning variables, I see some aligning the equals sign (=) using spaces while others just use a space before and after the equals sign.

See https://groups.google.com/forum/#!topic/php-fig/1mEA_cDA5dM

**Comment by hrvoj3e** [comment]
It is more readable to align equal signs.
(see pattern I use in screenshot below)

![image](https://cloud.githubusercontent.com/assets/4988133/17854066/5ba68198-6870-11e6-9924-618eb2fc28e8.png)

**Comment by rob006** [comment]
Alignment creates bigger diffs and more merge conflicts. Imagine that you add another var `$array_really_long_name` - you need change all lines in block just to keep alignment.

**Comment by hrvoj3e** [comment]
@rob006 True. Didn't think of that.

**Comment by samdark** [comment]
I think both are readable. I'm used to exactly one space because it's both easier to type and there are less diff conflicts.

**Comment by linaori** [comment]
Internally my company is forcing alignments (for readability), however I start noticing that we have cases like this:

``` php
$this->em                           = $em;
$this->some_very_long_variable_name = $some_very_long_variable_name;
```

Especially when writing unit-tests or methods with several assignments (to avoid calling methods more than once), this is a bit of an issue. I notice people (including myself) start "hacking" around the codestyle by adding a blank line and grouping variables based on length:

``` php
$contract = ...;
$option   = ...;

$contract_option1 = ...;
$contract_option2 = ...;
```

I think this is counter productive.

**Comment by glen-84** [comment]
I don't think that this should be enforced either way.

**Comment by PowerKiKi** [comment]
I am in favor of allowing only exactly 1 space before and after the equals sign and nothing else.

**Comment by michaelcullum** [comment]
Korvin and I discussed this and PSR-12 explicitly says `[assignment] operators MUST be preceded and followed by at least one space` meaning both alignment and non-alignment are okay.

**Comment by PowerKiKi** [comment]
It seems to me that this issue title and the quoted message have slightly different meaning. The quote seems to ask which style should be enforced, while the title asks whether we should enforce something. So to me the resolution to do nothing at all does not solve the issue raised by the quote.

Was it ever considered to enforce either styles ? or was is only considered whether the alignement should be _allowed_ ?

**Comment by michaelcullum** [comment]
Essentially what we're saying is 'no we shouldn't enforce either, but should allow both'.

Does that clarify?

**Comment by PowerKiKi** [comment]
The conclusion was clear, but my concern (and I believe also OP's concern), is more "Why did you not choose to enforce 1 style and disallow the other one ?"

I may be wrong, but I had the feeling that PSR-2 was seen as too permissive and that PSR-12 should be more strict by covering more syntaxes in more details. If that is true, then I think the conclusion here is not enough to reach that goal and 1 of the 2 styles should be picked to be enforced.

One a side-note are the survey results publicly available somewhere ?

**Comment by samdark** [comment]
Survey results are prepared to be published.
