### ISSUE TITLE
PHP 7.1

### ISSUE THREAD

**Issue by samdark** [cs-extended/fig-standards#39]
From [Iltar van der Berg ML message](https://groups.google.com/forum/#!topic/php-fig/beBQqv6PEyc):

Multiple exceptions in one catch:
https://wiki.php.net/rfc/multiple-catch

Class constant visibility modifiers:
https://wiki.php.net/rfc/class_const_visibility

Nullable arguments and return types: 
https://wiki.php.net/rfc/nullable_types

List() with keys:
https://wiki.php.net/rfc/list_keys

Short syntax for list():
https://wiki.php.net/rfc/short_list_syntax

**Comment by michaelcullum** [comment]
Korvin and I discussed this and we agreed we should leave list() functionality but cover iterable, multiple catch, constant visibility, and nullable types in PSR-12.

**Comment by samdark** [comment]
Why leaving `list()`?

**Comment by michaelcullum** [comment]
It will be controversial, is quite complex to document for a small thing, and we have nothing to work from at all on how we might handle it in the spec so would basically just be guessing. The others will all be rather uncontroversial so the lack of a survey is not a huge problem and they can all take precedence from similar things already covered within the spec.

**Comment by linaori** [comment]
Personally I'd treat `list() =` vs `[] =` as `= array()` vs `= []`, which I don't think are listed in either codestyle PSRs. I did feel it was important to mention them as 7.1 feature though.

**Comment by michaelcullum** [comment]
Done
