### ISSUE TITLE
Using "self" keyword instead of classname

### ISSUE THREAD

**Issue by dave1010** [cs-extended/fig-standards#6]
These do the same thing and AFAIK are just a coding style difference. Can PSR-12 cover this?

```
class Foo
{
    public static function create()
    {
        return new Foo();
    }
}
```

vs

```
class Foo
{
    public static function create()
    {
        return new self();
    }
}
```

**Comment by michaelcullum** [comment]
This is a breaking change so unless ~80% of FIG projects who are currently using PSR-2 are doing one way over the other, I'd rather just leave this.

Could do it as a SHOULD, not MUST.

**Comment by KorvinSzanto** [comment]
I agree that these are coding style differences, but I'm not sure that we'd have enough of a consensus or demand to make a judgement on it. I think we should probably bring this up on the mailing list and see what other projects think.

**Comment by michaelcullum** [comment]
Most projects use the former and not the latter but this will cause rather large breaks and I'd rather avoid that as I'd like to make adoption not too painless. I'll put something on the ML and gather opinions there.

**Comment by joe-meyer** [comment]
It seems reasonable to me to think that this could be standardized, but when I think about it more often than not I really should/want to be using `static` as opposed to the classname or self so in the end I almost feel like it's a moot point.

**Comment by michaelcullum** [comment]
I'm actually now thinking this is kind of out of scope but if you do think it should be there, feel free to bring it up on the ML for a larger discussion. :)

**Comment by keradus** [comment]
BTW, PHP CS Fixer may do it for any willing to have it:

> **self_accessor**
> Inside a classy element "self" should be preferred to the class name itself.

it would be great to have it in PSR ;)

**Comment by michaelcullum** [comment]
@KorvinSzanto Can your script be easily adapted to scan for this?
