### ISSUE TITLE
Type Hints/Declarations

### ISSUE THREAD

**Issue by michaelcullum** [cs-extended/fig-standards#8]
Type hinting SHOULD be done in parameters through type hints where possible and when available in minimum required version?
MUST be lowercase?

**Comment by michaelcullum** [comment]
@KorvinSzanto Other than case is there anything else to say about type hints?

**Comment by KorvinSzanto** [comment]
Parent and self?

**Comment by michaelcullum** [comment]
What do you mean?

**Comment by michaelcullum** [comment]
b10e50a350aa078fabbc383c5b1b34d9d7d3688b
